### PR TITLE
This might be stupid

### PR DESCRIPTION
**Pull request by Lemon-Cannon**
Attempted to make a log that says if the player uses a spell so that the enemy entity can do damage to it and punish the player if he tries to do anything special. I have no clue about the code, but based on what I figured, it works like as so.

### CODE REVIEW

**Comment by Lemon-Cannon** [comment]
@Felix-44

**Comment by Lemon-Cannon** [comment]
@DarkBrick  gimme a check

**Comment by Lemon-Cannon** [comment]
This is only a test, so I haven't made an enemy ai yet. I also figured out why I can't edit dark bricks file. It's because it's in draft mode, which means only people with write permissions can touch it.

**Comment by Lemon-Cannon** [comment]
SImply get it out of draft mode, and I should be able to edit.

**Comment by Felix-44** [comment]
Interesting

**Comment by Lemon-Cannon** [comment]
@Felix-44 the real question is, does it work?

**Comment by Felix-44** [comment]
it should, can't check it today (its late)

**Comment by Felix-44** [comment]
I came up with a player-only way to do this in a less hardcoded way, so I'll close this for now

**Pull request closed without merging**
