### PR TITLE
feat: add debug command

### PR DESCRIPTION
**Pull request by LJMSU**
This PR:
- Adds the `&debug` command.

`&debug` is a much more powerful version of `&eval`, and is restricted to members of the official Xilef server which has the developer role.

### CODE REVIEW

**Comment by Felix-44** [comment]
you forgot to move the other developer commands in developer.js
if thats what you wanted to do (I assume so by the file name)

**Comment by LJMSU** [comment]
I forgot to do that and I'm already on phone :v_:.

**Comment by Felix-44** [comment]
want me to do it?

**Comment by LJMSU** [comment]
yes pls

**Comment by Felix-44** [comment]
okay

**Pull request merged**
