### PR TITLE
chore(.gitignore): add more items in .gitignore

### PR DESCRIPTION
**Pull request by LJMSU**
This PR:
- Add some common items to `.gitignore `

These items SHOULD be ignored, as they are automatically generated or unnecessary. Taken from https://github.com/github/gitignore/blob/master/Node.gitignore

### CODE REVIEW

**Comment by Felix-44** [comment]
Wouldnt this ignore all the Node modules things?

**Comment by LJMSU** [comment]
No. You would still have the folder locally, but everytime you clone the repository, you would have to execute `npm i`.

**Comment by Felix-44** [comment]
> No. You would still have the folder locally. But everytime you clone the repository, you would have to execute `npm i` (this installs _every_ dependency automatically). npm stores all the package's dependencies info (name, version, etc.) in `package.json`, so don't worry about your code breaking because of a version mismatch.

well, that would require more time every time, is there a reason as to why it should remain gitignored?
technically, even if ignored, the file would still have to be deleted, right?

**Comment by LJMSU** [comment]
> is there a reason as to why it should remain gitignored?
Yes. `node_modules` can get very large as time goes on (10+ MB), and it could also save some time for git.

> technically, even if ignored, the file would still have to be deleted, right?
What? The folder is ignored in git, but not for you. This saves time for git because git doesn't have to manage that folder (because it is already managed by npm). Even if the folder is gone, you could always do `npm i`, which would take about ~2 seconds every time on my computer. Everything would still stay the same, except that there are no `node_modules` in this repository.

**Comment by Felix-44** [comment]
> except that there are no node_modules in the github repository.

But that folder is _already_ in the repository

**Comment by LJMSU** [comment]
Let's think of this in a different way. `.gitignore` ignores items so that git wouldn't track them, meaning git wouldn't put it in the source control. It would still be available in the file system to be accessed by anything else, it's just that git won't track them and put them here.

And your whole folder isn't a repository. It's the `.git/` folder that is the repository. So again, if you ignored `node_modules/`, it would be untracked in the git repository, but it would be still available in the folder.

**Comment by Felix-44** [comment]
But the folder would be useless and might become outdated eventually, so it should still removed

**Comment by LJMSU** [comment]
No no, when you update a package (`npm i package` or `npm update`), npm updates the `node_modules/` folder ***and*** the `dependencies` field in `package.json`. And when you run `npm i`, it automatically installs all packages you have in the `dependencies` field with their versions, so if you update your packages *properly* someone that cloned your repository would have the same version of a package with you, and thus there would be no outdated folders (unless your version is outdated then everyone's version will also be outdated).

Or maybe you're thinking that `package.json` would be ignored too? It won't, don't worry.

**Comment by Felix-44** [comment]
the thing is, why would we have to keep the node_modules folder if we ignore it? thats what im not understanding, sorry

**Comment by LJMSU** [comment]
When you require a package (ex. `const Discord = require('discord.js')`), node searches for the local node_modules folder (https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders), NOT from the npm website itself. If there is no `node_modules/` folder, it would just error.

**Comment by Felix-44** [comment]
I know that, I meant the folder in the repository, not in my files

**Comment by LJMSU** [comment]
Sorry, I'm a little bit confused here too. Are you saying that `node_modules/` would still be saved by git even after ignoring it? While yes, it does, but only in the commit history. The latest commit would have

**Comment by LJMSU** [comment]
> either way, I'll merge this soon, but I would still like to understand this thing first

Thank you. If you'd like to understand it a bit more, I could send you some links at discord.

**Pull request merged**
