### PR TITLE
feat: prefix command

### PR DESCRIPTION
**Pull request by LJMSU**
This PR:
- Adds a `prefix` command

This command will change the prefix *per server*, and it will be stored in `src/Data/prefixes.json`

### CODE REVIEW

**Comment by LJMSU** [comment]
Note that this PR is still a WIP.

**Comment by Felix-44** [comment]
wait, some of the strings you changed with prefix.get are defined at the start, wont that make them the same for everyone?

**Review by Felix-44 — APPROVED** [review]
Everything seems alright, though I would like an explenation of how general.js works

**Comment by LJMSU** [comment]
1. I feel this is a hard topic, so I feel like we should discuss this on discord.
2. `general.j`s adds the Prefix namespace since I don't know where to put it.

**Pull request merged**
