### PR TITLE
feat(driller): add driller repair max

### PR DESCRIPTION
**Pull request by LJMSU**
This PR:
- Adds the `max` value for the `driller repair` command

Adds the `max` value for the `driller repair` command, which repairs the driller to max health without losing any DogeCoins.

### CODE REVIEW

**Comment by Felix-44** [comment]
I see an issue, the math uses `Driller.hp`, which doesn't exist
`Driller` is the object which has all the values for the driller games (like the ores or the prices for tiers), but for the stats of the current player you have to use `DrillerGame`

**Comment by LJMSU** [comment]
I forgot, sorry. It's now fixed.

**Comment by Felix-44** [comment]
okay, I dont understand why randomly decided to reformat the entire file..but everything check out

**Comment by LJMSU** [comment]
This is why i made #10

**Comment by Felix-44** [comment]
I guess the tables have turned then

**Comment by LJMSU** [comment]
Should i make another PR to fix it? Or would you do that?

**Comment by Felix-44** [comment]
what do you mean?

**Comment by LJMSU** [comment]
Should I make another PR that reverts the formatting?

**Comment by Felix-44** [comment]
for that you can commit it directly, I guess?

**Comment by LJMSU** [comment]
Ok, I will.

**Pull request merged**
