### PR TITLE
fix shutdown since bot runs on linux now

### PR DESCRIPTION
**Pull request by Volas171**
Ù

### CODE REVIEW

**Comment by Felix-44** [comment]
Didnt it work already?
Also that code is for restarting, (&shutdown can restart too)

**Comment by Volas171** [comment]
> Didnt it work already? 

it just crashed because of the cmd.exe not being a thing

> Also that code is for restarting, (&shutdown can restart too)
yeah I fixed on the second commit

**Comment by Felix-44** [comment]
But..what makes it restart now?

**Comment by Volas171** [comment]
the panel

**Comment by Felix-44** [comment]
are you sure? doing &shutdown without restarting did close the panel too
(the panel is the console in the site I assume)

**Comment by Volas171** [comment]
im sure this will work, tested it

**Pull request merged**
